### ISSUE TITLE
Create register page

### ISSUE THREAD

**Issue by TalarMustafa** [tiffsoa/-Code_Monkies-SOEN341_Project_F24-#1]
- Frontend: Register page css
- Frontend: Need to add extra options when registering (teacher or instructor radio buttons, name, email)
- Backend: Need to add extra columns to database (teacher or instructor Boolean, name, email)
- Backend: When registering, need to add into database the extra data (teacher or instructor, name, email) which is now also coming from the frontend

**Comment by Mohammed-Janoudi** [comment]
the instructor/teacher backend part is added

**Comment by Transyfor** [comment]
Frontend:
            - Missing username box
Backend:   
         - view retrieves form element named “instructor” which doesn’t exist
            - When inputing a new entry into the user table, instructor is set to a string but the database takes a boolean for that collumn
            - It shouldn't be set to "on" by default
