### ISSUE TITLE
Display “Rate team member n” page

### ISSUE THREAD

**Issue by v3r1510** [tiffsoa/-Code_Monkies-SOEN341_Project_F24-#56]
- Rating page displays the name of the user currently being rated 
- Has radio buttons to rate a student based off on 4 concepts: Cooperation, Conceptual Contribution, Practical Contribution, and Work Ethic. 
- The evaluator (student) can also leave a comment.

**Comment by Transyfor** [comment]
Don't forget the comment box and the submit button
