### ISSUE TITLE
Export student team ratings to CSV

### ISSUE THREAD

**Issue by tiffsoa** [tiffsoa/-Code_Monkies-SOEN341_Project_F24-#99]
Implement a view to export the team ratings data to a CSV file
- Write CSV headers and populate data rows
- Set up HTTP response with CSV file download

**Comment by Transyfor** [comment]
Looks excellent

**Comment by Transyfor** [comment]
When downloading CSV, student gets the ratings that they gave for another student in the csv file (which they shouldnt)

**Comment by tiffsoa** [comment]
Fixed the bug in issue 105
